services:
  gqrx:
    init: true
    environment:
      DISPLAY:
      PULSE_SERVER: /run/pulse/native # this must match below
    build: 
      context: .
      dockerfile: Dockerfile
    user: 0:0
    image: qgrx:develop
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$PWD:/opt/project"
      - "$PWD/config:/root/.config"
      - "$PWD/log:/root/.local/share"
      - "$PWD/.config/gqrx:/root/.config/gqrx"
      - "/dev/shm:/dev/shm"
      - "/run/user/1000/pulse:/run/pulse:ro" # this much match above
      - "/var/lib/dbus:/var/lib/dbus"
      - "/dev/snd:/dev/snd"
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/bus/usb/001/005"
    network_mode: "host"
    command:
      - /bin/bash
    working_dir: /opt/project
